-
  name: 'api'
  version: ''
-
  name: 'iam'
  version: 'v1'
-
  name: 'longrunning'
  version: ''
-
  name: 'rpc'
  version: ''
-
  name: 'type'
  version: ''
-
  name: 'logging/type'
  version: ''
