# Configures the version of the dependencies of various generated packages, and
# related information.

auth:
  python:
    version: '1.4.11'
  ruby:
    version: '0.4.1'
  nodejs:
    version: '0.9.7'

grpc:
  core:
    version: '0.9.0'
  objc:
    version: '0.5.0'
    ios:
      deployment_target: '6.0'
    osx:
      deployment_target: '10.8'
  python:
    version: '0.11.0b1'
  ruby:
    version: '0.12.0'
  nodejs:
    version: '0.12.0'

protobuf:
  python:
    version: '3.0.0b2'
  ruby:
    version: '3.0.0.alpha.5.0'

googleapis_common_protos:
  python:
    version: '1.0.0'
  ruby:
    version: '*'
